# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: create-pr

on:
  push:
    branches: [ dev ]


jobs:

  pr_to_master:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v1
          - name: pull-request
            uses: repo-sync/pull-request@v2
            with:
                source_branch: 'dev' # If blank, default: triggered branch
                destination_branch: 'master'
                pr_label: automerge
                github_token: ${{ secrets.GITHUB_TOKEN }}

