# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: merge | build | publish

on:
  push:
    branches: [ dev ]

jobs:

  merge-branch:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: merge-build-publish
      uses: devmasx/merge-branch@v1.1.0
      with:
        target_branch: 'test/merge-and-build-test'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: true
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.4.2
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
