# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI and deploy

on:
  push:
    branches: [ test/merge-and-build-test ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
          npm ci
          npm run build --if-present

    - uses: actions/upload-artifact@v2
      name: create artifact
      with:
        name: deploy-artifact
        path: docs

      env:
        CI: "true"
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download math result for job 1
      uses: actions/download-artifact@v1
      with:
        name: deploy-artifact
        path: docs

    - uses: JamesIves/github-pages-deploy-action@releases/v3
      name: Deploy 🚀
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs # The folder the action should deploy.
